name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.2'
        if: matrix.os == 'windows-latest'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set package version
        run: pnpm pkg set version=${{ github.ref_name }} --prefix apps/sentry-client-desktop

      - name: Install dependencies
        run: pnpm install

      - name: Build monorepo
        run: pnpm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WINDOWS_SIGN_USER_NAME: ${{ secrets.SSL_USERNAME }}
          WINDOWS_SIGN_USER_PASSWORD: ${{ secrets.SSL_PASSWORD }}
          WINDOWS_SIGN_USER_TOTP: ${{ secrets.SSL_TOTP_SECRET }}

      - name: Upload sentry-client-desktop artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-sentry-client-desktop-${{ matrix.os }}
          path: apps/sentry-client-desktop/release

      - name: zip cli artifacts
        run: |
          cd apps/cli/release
          zip sentry-node-cli-macos.zip sentry-node-cli-macos
          zip sentry-node-cli-linux.zip sentry-node-cli-linux
        if: matrix.os == 'ubuntu-latest'

      - name: Upload cli artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-cli-${{ matrix.os }}
          path: apps/cli/release

  sign-and-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-sentry-client-desktop-macos-latest/latest-mac.yml
            release-sentry-client-desktop-macos-latest/sentry-client-macos.dmg.blockmap
            release-sentry-client-desktop-macos-latest/sentry-client-macos.dmg
            release-sentry-client-desktop-ubuntu-latest/latest-linux.yml
            release-sentry-client-desktop-ubuntu-latest/sentry-client-linux.AppImage
            release-cli-ubuntu-latest/sentry-node-cli-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
